### ISSUE TITLE
Feat: 좋아요 관련 기능 구현

### ISSUE THREAD

**Issue by dev-junehee** [yoonwooiOS/PocketTheater#24]
##  📌 Overview
- 좋아요 관련 기능을 구현합니다.

<br />

## ✔️ Todo
- [ ] 상세 화면 - 좋아요 추가
- [ ] 상세 화면 - 재생 화면 연결
- [ ] 상세 화면 - overview height dynamic 처리
- [ ] 좋아요 탭 - 좋아요 삭제

<br />

## 🔗 References
- []()
- https://ios-development.tistory.com/1015

<br />
